import Head from "next/head";
import styled from "@emotion/styled";
import { InferGetStaticPropsType } from "next";
import Link from "next/link";
import FeedbackForm from "@components/FeedbackFrom";

const List = styled.ol``;
const ListItem = styled.li`
  padding: 8px;
`;

export default function Home({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>Blog Build With TS, Next.js and Miligram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Blog Build With TS, Next.js and Miligram</h1>
      </header>
      <div className="row">
        <div className="col">
          <List>
            {posts.map((post) => (
              <ListItem key={post.id}>
                <Link href="/post/[id]" as={`/post/${post.id}`}>
                  {post.title}
                </Link>
              </ListItem>
            ))}
          </List>
        </div>
        <div className="col">
          <FeedbackForm />
        </div>
      </div>
    </div>
  );
}

export type Post = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts: Post[] = await res.json();

  return {
    props: {
      posts,
    },
  };
}
